server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: sales
          uri: http://localhost:8082
          predicates:
            - Path=/orderManagements/**, 
        - id: personInCharge
          uri: http://localhost:8083
          predicates:
            - Path=/personInCharges/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: sales
          uri: http://sales:8080
          predicates:
            - Path=/orderManagements/**, 
        - id: personInCharge
          uri: http://personInCharge:8080
          predicates:
            - Path=/personInCharges/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
