---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  labels:
    app: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
        - name: sales
          image: username/sales:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: personInCharge
  labels:
    app: personInCharge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personInCharge
  template:
    metadata:
      labels:
        app: personInCharge
    spec:
      containers:
        - name: personInCharge
          image: username/personInCharge:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: sales
  labels:
    app: sales
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sales


---


apiVersion: v1
kind: Service
metadata:
  name: personInCharge
  labels:
    app: personInCharge
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: personInCharge

